c-----*-----------------------------------------------------------------

c include file for metronew.f that defines additional control parameters

      integer m_ndmax
      parameter (m_ndmax=100)    ! max. no. of dimensions

      integer m_ncmax
      parameter (m_ncmax=100)   ! max. no. of chains

      integer m_nengmax
      parameter (m_nengmax=6)   ! max. no. of MCMC engines available

c-----*-----------------------------------------------------------------











